
server:
  port: 5010

spring:
  application:
    title: Application gateway
    version: 1.0
    name: gateway


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"

      routes:
        - id: moodbooster-service
          uri: http://localhost:3500
          predicates:
            - Path=/moodbooster/**
          filters:
            - RewritePath=/moodbooster/(?<segment>.*), /v1.0/invoke/moodbooster-service/method/$\{segment}
        - id: user-service
          uri: http://localhost:3500
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /v1.0/invoke/user-service/method/$\{segment}
        - id: badge-service
          uri: http://localhost:3500
          predicates:
            - Path=/badge/**
          filters:
            - RewritePath=/badge/(?<segment>.*), /v1.0/invoke/badge-service/method/$\{segment}
        - id: challenge-service
          uri: http://localhost:3500
          predicates:
            - Path=/challenge/**
          filters:
            - RewritePath=/challenge/(?<segment>.*), /v1.0/invoke/challenge-service/method/$\{segment}
        - id: feed-service
          uri: http://localhost:3500
          predicates:
            - Path=/feed/**
          filters:
            - RewritePath=/feed/(?<segment>.*), /v1.0/invoke/feed-service/method/$\{segment}
        - id: event-service
          uri: http://localhost:3500
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/event/(?<segment>.*), /v1.0/invoke/event-service/method/$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/913b1a98-9696-4db5-b548-9e17b6d3fc68/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/913b1a98-9696-4db5-b548-9e17b6d3fc68/v2.0
          audiences: 215b09e4-54cb-49aa-837b-546f73fc29f6
