application:
  title: Moodbooster Service
  version: 1.0


server:
  port: 5001

spring:

  jpa:
    properties:
      hibernate:
        format_sql=true:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/913b1a98-9696-4db5-b548-9e17b6d3fc68/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/913b1a98-9696-4db5-b548-9e17b6d3fc68/v2.0
          audiences: 215b09e4-54cb-49aa-837b-546f73fc29f6

  data:
    mongodb:
      uri: ${CONNECTION_STRING}
      database: ${DB_NAME}
      auto-index-creation: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#spring:
#  config:
#    activate:
#      on-profile: dev
#  data:
#    mongodb:
#      uri: mongodb://localhost:3004
#      database: activities
#      auto-index-creation: true
