# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & test services

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  moodbooster-service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        # If the hash of the project files is the same, use cache.
        key: ${{ runner.os }}-m2-${{ hashFiles('services/moodbooster-service/pom.xml') }}
        restore-keys: ${{ runner.os}}-m2-
    - name: Build with Maven
      run: mvn -B package --file services/moodbooster-service/pom.xml
      
      
  user-service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        # If the hash of the project files is the same, use cache.
        key: ${{ runner.os }}-m2-${{ hashFiles('services/user-service/pom.xml') }}
        restore-keys: ${{ runner.os}}-m2-

    - name: Build with Maven
      run: mvn -B package --file services/user-service/pom.xml


  badge-service:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # If the hash of the project files is the same, use cache.
          key: ${{ runner.os }}-m2-${{ hashFiles('services/badge-service/pom.xml') }}
          restore-keys: ${{ runner.os}}-m2-

      - name: Build with Maven
        run: mvn -B package --file services/badge-service/pom.xml

  challenge-service:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # If the hash of the project files is the same, use cache.
          key: ${{ runner.os }}-m2-${{ hashFiles('services/challenge-service/pom.xml') }}
          restore-keys: ${{ runner.os}}-m2-

      - name: Build with Maven
        run: mvn -B package --file services/challenge-service/pom.xml

  gateway:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        # If the hash of the project files is the same, use cache.
        key: ${{ runner.os }}-m2-${{ hashFiles('gateway/pom.xml') }}
        restore-keys: ${{ runner.os}}-m2-

    - name: Build with Maven
      run: mvn -B package --file gateway/pom.xml


  feed-service:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # If the hash of the project files is the same, use cache
          key: ${{ runner.os }}-m2-${{ hashFiles('services/feed-service/pom.xml') }}
          restore-keys: ${{ runner.os}}-m2-
      - name: Build with Maven
        run: mvn -B package --file services/feed-service/pom.xml

  event-service:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # If the hash of the project files is the same, use cache.
          key: ${{ runner.os }}-m2-${{ hashFiles('services/event-service/pom.xml') }}
          restore-keys: ${{ runner.os}}-m2-

      - name: Build with Maven
        run: mvn -B package --file services/event-service/pom.xml

