name: docker-compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
env: 
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:  
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        # If the hash of the project files is the same, use cache.
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os}}-m2-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v1
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#     - name: Pull user service image
#       run: docker pull ghcr.io/vitaquest/user-service:latest
#     - name: Pull activity service
#       run: docker pull ghcr.io/vitaquest/activity-service:latest
    - name: Build and run docker compose stack
      run: docker compose up -d
    - name: Check running containers
      run: docker ps -a
